services:
  db:
    image: docker.m.daocloud.io/library/mysql:8.0
    container_name: ev_charging_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ev_charging
    volumes:
      - ev_charging_mysql_data:/var/lib/mysql

  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    container_name: ev_station_redis
    restart: always

  user_service:
    build: ./services/user_service
    container_name: user_service
    ports:
      - "18010:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/ev_charging

  station_service:
    build: ./services/station_service
    container_name: station_service
    ports:
      - "18011:8001"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/ev_charging
      - REDIS_URL=redis://redis:6379/0

  charging_service:
    build: ./services/charging_service
    container_name: charging_service
    ports:
      - "18012:8002"
    depends_on:
      - db
      - station_service
      - redis
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/ev_charging
      - STATION_SERVICE_URL=http://station_service:8001
      - REDIS_URL=redis://redis:6379/0

  forecasting_service:
    build: ./services/forecasting_service
    container_name: forecasting_service
    ports:
      - "18013:8003"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/ev_charging

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "18080:8080"
    depends_on:
      - user_service
      - station_service
      - charging_service
      - forecasting_service

volumes:
  ev_charging_mysql_data:
