services:
  db:
    image: docker.m.daocloud.io/library/mysql:8.0
    container_name: intellishop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intelli_shop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    container_name: ev_station_redis
    restart: always
    ports:
      - "6379:6379"

  user_service:
    build: ./services/user_service
    container_name: user_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/intelli_shop

  station_service:
    build: ./services/station_service
    container_name: station_service
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/intelli_shop
      - REDIS_URL=redis://redis:6379/0

  charging_service:
    build: ./services/charging_service
    container_name: charging_service
    ports:
      - "8002:8002"
    depends_on:
      - db
      - station_service
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/intelli_shop
      - STATION_SERVICE_URL=http://station_service:8001

  forecasting_service:
    build: ./services/forecasting_service
    container_name: forecasting_service
    ports:
      - "8003:8003"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/intelli_shop

volumes:
  mysql_data:
